build_image:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.contair.org:5005
    - docker build -t git.contair.org:5005/docker-container/nginx-php .
    - docker push git.contair.org:5005/docker-container/nginx-php
