image: docker:latest
services:
- docker:dind

stages:
- build
- release

variables:
  CONTAINER_BUILD_IMAGE: registry.mobilistics.de/nginx-php:${CI_BUILD_REF}
  CONTAINER_RELEASE_IMAGE: registry.contair.org/nginx-php:php5.5
  CONTAINER_MOBI_RELEASE_IMAGE: registry.mobilistics.de/nginx-php:php5.5

before_script:
  - docker login --username=${REGISTRY_USERNAME} --password=${REGISTRY_PASSWORD} registry.contair.org

build:
  stage: build
  script:
    - docker build --pull --no-cache -t ${CONTAINER_BUILD_IMAGE} .
    - docker push ${CONTAINER_BUILD_IMAGE}
    - echo "Successfull pushed image ${CONTAINER_BUILD_IMAGE}"

release-image:
  stage: release
  script:
    - docker pull ${CONTAINER_BUILD_IMAGE}
    - docker tag ${CONTAINER_BUILD_IMAGE} ${CONTAINER_RELEASE_IMAGE}
    - docker tag ${CONTAINER_RELEASE_IMAGE} ${CONTAINER_MOBI_RELEASE_IMAGE}
    - docker push ${CONTAINER_RELEASE_IMAGE}
    - echo "Successfull pushed image ${CONTAINER_RELEASE_IMAGE}"
  only:
    - php5.5
