image: docker:latest
services:
- docker:dind

stages:
- build
- test
- release

variables:
  DOCKER_DRIVER: overlay
  CONTAINER_BUILD_IMAGE: registry.contair.org/nginx-php:${CI_BUILD_REF}
  CONTAINER_RELEASE_IMAGE: registry.contair.org/nginx-php:php7.0

before_script:
  - docker login --username=${REGISTRY_USERNAME} --password=${REGISTRY_PASSWORD} registry.contair.org

build:
  stage: build
  script:
    - docker build --pull --no-cache -t ${CONTAINER_BUILD_IMAGE} .
    - docker push ${CONTAINER_BUILD_IMAGE}
    - echo "Successfull pushed image ${CONTAINER_BUILD_IMAGE}"

test:
  stage: test
  script:
    - apk add --no-cache ruby build-base ruby-dev
    - gem install --no-ri --no-rdoc serverspec docker-api
    - docker pull ${CONTAINER_BUILD_IMAGE}
    - IMAGEID=`docker images -q ${CONTAINER_BUILD_IMAGE}`
    - docker images -q ${CONTAINER_BUILD_IMAGE}
    - echo $IMAGEID
    - rspec Dockerfile_spec.rb
    

release-image:
  stage: release
  script:
    - docker pull ${CONTAINER_BUILD_IMAGE}
    - docker tag ${CONTAINER_BUILD_IMAGE} ${CONTAINER_RELEASE_IMAGE}
    - docker push ${CONTAINER_RELEASE_IMAGE}
    - echo "Successfull pushed image ${CONTAINER_RELEASE_IMAGE}"
  only:
    - php7.0