version: "2"
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - POSTFIX_HOSTNAME=test.com

  memcache:
    image: memcached:1.5

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=test
